### ISSUE TITLE
Some questions about chossing the embeddings

### ISSUE THREAD

**Issue by HelloWorldLTY** [yiqunchen/GenePT#4]
Hi, nice work. I notice that you used NCBI text as input to generate the gene embeddings, but in this notebook "gene_embeddings_examples.ipynb":

You used different propmt comparing with NCBI text to generate the explaniation of such gene.
```
gene_completion_test = ['ALPP']
for gene in sorted(gene_completion_test):
    if gene not in gene_name_to_GPT_response:
        print('gene name',gene)
        completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", 
                    messages=[{"role": "user", "content": f"Tell me about gene {gene}"}])
        gene_name_to_GPT_response[gene] = completion.choices[0].message.content
```

My question is that why we cannot directly pick the generation text of gpt-3.5/4 of a gene as input and get its embeddings, since it seems that there is no halluciation for these genes. Thanks a lot.

**Comment by yiqunchen** [comment]
Thanks a lot for your great question! We started with the NCBI database because it's high quality, curated summary of genetic information. On the other hand, we only had the capacity to verify that GPT did not hallucinate on several hundred genes without an NCBI page -- definitely an interesting direction see how to validate this at scale (e.g., through text embeddings).
